<?php
    session_start();
    include('includes/header.php');
    include('html/profil.php');
    include('mains/grade.php');
    include('mains/new_subject.php');
    include('mains/new_meeting.php');
    include('includes/footer.php');
?>